package team1.project3.quizlist;

import com.intellij.uiDesigner.core.GridLayoutManager;
import team1.project3.service.IView;
import javax.swing.*;
import java.awt.*;
import java.util.List;


public class QuizListView extends JPanel implements IView {
    public JPanel getPanel() {
        return panel;
    }

    private JPanel panel;
    private JButton navigateToQuizPageButton;

    public JButton getNavigateToQuizPageButton() {
        return navigateToQuizPageButton;
    }

    public QuizListView() {
        $$$setupUI$$$();

    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel = new JPanel();
        panel.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        panel.setBackground(new Color(-12828863));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel;
    }


}
